[app]
name = "hcanranbapi"
version = "0.7"

[extensions]
allowed = ["png", "jpg", "jpeg", "gif", "webp"]

[limiter]
# 每个IP每分钟最多请求次数
requests_per_minute = 120

[paths]
# 使用相对于项目根目录的路径
base_dir = "var"
project_root = "."
theme_dir = "usr/theme"
image_base = "usr/img"
text_base = "usr/text"
